import type { Player } from '@/lib/types'
import squadsJson from './squads.json'

// Generated by: pnpm precompute:squads
// Source: WC 2026 squad data from football-data.org, goal rates from WC 2026 scorers.
// Run pnpm precompute:squads to refresh with current squads and scorer data.
export const squadsByTeamId: Record<number, Player[]> = Object.fromEntries(
  Object.entries(squadsJson).map(([k, v]) => [Number(k), v as Player[]])
)
