const FLAGS: Record<string, string> = {
  // World Cup 2026 teams
  Mexico: '🇲🇽',
  'South Korea': '🇰🇷',
  'South Africa': '🇿🇦',
  Czechia: '🇨🇿',
  Switzerland: '🇨🇭',
  Canada: '🇨🇦',
  'Bosnia-Herzegovina': '🇧🇦',
  Qatar: '🇶🇦',
  Brazil: '🇧🇷',
  Morocco: '🇲🇦',
  Haiti: '🇭🇹',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'United States': '🇺🇸',
  Australia: '🇦🇺',
  Turkey: '🇹🇷',
  Paraguay: '🇵🇾',
  Ecuador: '🇪🇨',
  Germany: '🇩🇪',
  'Ivory Coast': '🇨🇮',
  'Curaçao': '🇨🇼',
  Japan: '🇯🇵',
  Sweden: '🇸🇪',
  Tunisia: '🇹🇳',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  'New Zealand': '🇳🇿',
  Egypt: '🇪🇬',
  Colombia: '🇨🇴',
  Uruguay: '🇺🇾',
  Spain: '🇪🇸',
  'Cape Verde Islands': '🇨🇻',
  'Saudi Arabia': '🇸🇦',
  Argentina: '🇦🇷',
  France: '🇫🇷',
  Portugal: '🇵🇹',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Italy: '🇮🇹',
  Croatia: '🇭🇷',
  Senegal: '🇸🇳',
  Ghana: '🇬🇭',
  Cameroon: '🇨🇲',
  Nigeria: '🇳🇬',
  Iran: '🇮🇷',
  Poland: '🇵🇱',
  Denmark: '🇩🇰',
  Wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Costa Rica': '🇨🇷',
  Panama: '🇵🇦',
  Honduras: '🇭🇳',
  Jamaica: '🇯🇲',
  Venezuela: '🇻🇪',
  Peru: '🇵🇪',
  Chile: '🇨🇱',
  Bolivia: '🇧🇴',
  Slovenia: '🇸🇮',
  Slovakia: '🇸🇰',
  Serbia: '🇷🇸',
  Ukraine: '🇺🇦',
  Austria: '🇦🇹',
  Romania: '🇷🇴',
  Greece: '🇬🇷',
  Norway: '🇳🇴',
  Finland: '🇫🇮',
  Albania: '🇦🇱',
  Hungary: '🇭🇺',
  China: '🇨🇳',
  Algeria: '🇩🇿',
  Mali: '🇲🇱',
  Benin: '🇧🇯',
  Tanzania: '🇹🇿',
  Comoros: '🇰🇲',
  'Burkina Faso': '🇧🇫',
  Angola: '🇦🇴',
  Iraq: '🇮🇶',
  Uzbekistan: '🇺🇿',
  Indonesia: '🇮🇩',
  Thailand: '🇹🇭',
  Vietnam: '🇻🇳',
  Philippines: '🇵🇭',
  India: '🇮🇳',
  Jordan: '🇯🇴',
  'Congo DR': '🇨🇩',
}

export function getFlag(name: string): string {
  return FLAGS[name] ?? ''
}
